version: '3.8'

services:
  redis-node-1:
    image: redis:7.0-alpine
    container_name: redis-node-1
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7000:6379"
    volumes:
      - redis-data-1:/data
    networks:
      - redis_cluster_net

  redis-node-2:
    image: redis:7.0-alpine
    container_name: redis-node-2
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:6379"
    volumes:
      - redis-data-2:/data
    networks:
      - redis_cluster_net

  redis-node-3:
    image: redis:7.0-alpine
    container_name: redis-node-3
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:6379"
    volumes:
      - redis-data-3:/data
    networks:
      - redis_cluster_net

  redis-node-4:
    image: redis:7.0-alpine
    container_name: redis-node-4
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:6379"
    volumes:
      - redis-data-4:/data
    networks:
      - redis_cluster_net

  redis-node-5:
    image: redis:7.0-alpine
    container_name: redis-node-5
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7004:6379"
    volumes:
      - redis-data-5:/data
    networks:
      - redis_cluster_net

  redis-node-6:
    image: redis:7.0-alpine
    container_name: redis-node-6
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7005:6379"
    volumes:
      - redis-data-6:/data
    networks:
      - redis_cluster_net

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5:
  redis-data-6:


networks:
  redis_cluster_net:
    driver: bridge
